### ISSUE TITLE
Extra space in tabbed codeblock in po2md output

### ISSUE THREAD

**Issue by dingyifei** [mondeja/mdpo#92]
It seems like the empty lines inside the tab style code block are filled with 4 spaces that doesn't exist in the original md files.

Could be related to #86 

![图片](https://user-images.githubusercontent.com/15083013/116552397-8c738180-a92b-11eb-90b6-cfcec8810695.png)

**Comment by mondeja** [comment]
[This is allowed by the CommonMark spec](https://spec.commonmark.org/dingus/?text=%20%20%20%20a%20simple%0A%20%20%20%20%0A%20%20%20%20indented%20code%20block%0A%20%20%20%20%0A%20%20%20%20hello%0A) and doesn't change the produced AST. Keep in mind that the goal of po2md is to reproduce the same valid Markdown AST with translations replaced, not to rebuild the same input format. Are you experiencing some downside due to this change?

**Comment by dingyifei** [comment]
The Klipper project I'm currently contributing to has a white space check for the markdown files. I thought it's a strange behavior of changing the code block. Now when I'm looking at it, I think I should probably talk to maintainer for the GitHub actions to see if we could skip those checks for the translated markdown files. 

Keeping mdpo simple and in spect is probably better than adding a feature that could introduce bugs and maintainability problems.

**Comment by mondeja** [comment]
I've opened #95 to track rendering format consistency expectations.

**Comment by mondeja** [comment]
Linking #152
